import Head from "next/head"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Upgrades</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3>This is only a small step for the POM token on Mars.</h3>
      <p>
        As the research from <b>MarsPioneersCorporation</b> advances, so will this humble project,
        and many more NFTs will be available.
      </p>
      <p>
        Part of the future upgrades include:
        <ul>
          <li>
            Sell your POM - Regretting your purchase? Wished you could be closer to the moon-lit
            side of Mars? Soon, you'll have the ability to sell your NFT to someone who really does
            not care, as long as they own a Plot On Mars.
          </li>
          <li>
            Co-Ownership - Can't afford a POM? Talk to your network, because soon, co-ownership of
            a POM will be possible!
          </li>
          <li>VF - Pour nos amis francophones, il y aura une version française à venir.</li>
          <li>What, isn't that enough for now?</li>
        </ul>
      </p>
    </div>
  )
}
